<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Error</title>
</head>
<body>

  <!-- JS的error处理 -->
  <script>
    // 常见的内置错误
    // 1. ReferenceError: 引用的变量不存在
    // console.log(a); // ReferenceError: a is not defined
    // console.log('------'); // 没有捕获到error（上面的出错代码没有处理），之后的代码都不会执行


    // 2. TypeError: 数据类型不正确的错误
    // let b;
    // // console.log(b.xxx); // TypeError: Cannot read property 'xxx' of undefined
    // b = {};
    // b.xxx(); // TypeError: b.xxx is not a function


    // 3. RangeError: 数据值不在其所允许的范围内
    // function fn(){
    //   fn();
    // }
    // fn(); // RangeError: Maximum call stack size exceeded


    // 4. SyntaxError: 语法错误
    // const c = """"; // SyntaxError: Unexpected string
  </script>


  <script>
    // 错误处理

    // 捕获错误: try ... catch
    try{
      let d;
      console.log(d.xxx);
    }catch(error){
      console.log(error.message); // message属性: 错误相关信息
      console.log(error.stack) // stack属性: 函数调用栈记录信息
    }
    console.log('出错之后');

    // 抛出错误: throw error
    function test(){
      if(Date.now() % 2){
        console.log('当前时间为奇数，可以执行');
      }else{ // 如果时间是偶数抛出异常，由调用来处理
        throw new Error('当前时间为偶数，无法执行')
      }
    }

    // 捕获处理异常
    try {
      test();
    }catch(error){
      alert(error.message)
    }


  </script>


</body>
</html>